site_name: FilmQADose
site_description: Documentation for the FilmQADose project
site_author: Eduardo Herrera
language: en

theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - header.autohide
    - toc.integrate
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.action.download
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

repo_url: https://github.com/eduardoh27/FilmQADose
repo_name: GitHub

nav:
  - Home: index.md
  - API Reference: api.md
  
plugins:
  - search
  - mkdocstrings:
      default_handler: python
