site_name: FilmQADose - Documentation
repo_url: https://github.com/eduardoh27/FilmQADose
repo_name: GitHub

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.svg

  palette:
    - scheme: default
      primary: teal      # cambia indigo por teal para un tono más fresco
      accent: amber
      toggle:
        icon: material/weather-night
        name: “Modo oscuro”
    - scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: “Modo claro”

  font:
    text: Roboto         # fuente sans-serif moderna
    code: Roboto Mono

  features:
    - navigation.instant
    - header.autohide    # oculta la cabecera al hacer scroll
    - toc.integrate
    - content.code.copy
    - content.action.edit

nav:
  - Home: index.md
  - API Reference: api.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: numpy