#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.6 on Wed Nov 18 22:27:12 2020
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class DialogoNormalizacion(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyDialog.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.radio_btn_1 = wx.RadioButton(self, wx.ID_ANY, "Maximo", style=wx.RB_GROUP)
        self.radio_btn_2 = wx.RadioButton(self, wx.ID_ANY, "Dosis fija")
        self.text_ctrl_1 = wx.TextCtrl(self, wx.ID_ANY, "")
        self.text_ctrl_1.Disable()
        self.radio_btn_3 = wx.RadioButton(self, wx.ID_ANY, "Elejir punto")
        self.button_1 = wx.Button(self, wx.ID_ANY, "Aceptar")
        self.button_2 = wx.Button(self, wx.ID_ANY, "Cancelar")
        self.resultado='cancelar'
        self.valor=0

        self.__set_properties()
        self.__do_layout()
        self.Bind(wx.EVT_RADIOBUTTON, self.desactivarCaja, self.radio_btn_1 )
        self.Bind(wx.EVT_RADIOBUTTON, self.desactivarCaja, self.radio_btn_3 )
        self.Bind(wx.EVT_RADIOBUTTON, self.activarCaja, self.radio_btn_2)

        self.Bind(wx.EVT_BUTTON, self.aceptar, self.button_1)
        self.Bind(wx.EVT_BUTTON, self.cancelar, self.button_2)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyDialog.__set_properties
        self.SetTitle("Normalizacion")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyDialog.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(self.radio_btn_1, 1, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_3.Add(self.radio_btn_2, 1, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_3.Add(self.text_ctrl_1, 1, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)
        sizer_2.Add(self.radio_btn_3, 1, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_4.Add(self.button_1, 1, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_4.Add(self.button_2, 1, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_2.Add(sizer_4, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_2)
        sizer_2.Fit(self)
        self.Layout()
        # end wxGlade
        
    def desactivarCaja(self,event):
        self.text_ctrl_1.Disable()
        
    def activarCaja(self,event):
        self.text_ctrl_1.Enable()
        
        
        

    def aceptar(self, event):  # wxGlade: MyDialog.<event_handler>
        if self.radio_btn_1.GetValue():
            self.resultado='maximo'
        elif self.radio_btn_2.GetValue():
            self.resultado='valorFijo'
            r=self.text_ctrl_1.GetValue()
            if r!='':
                self.valor=float(r)
        elif self.radio_btn_3.GetValue():
            self.resultado='select'
        self.Close()
    
        event.Skip()

    def cancelar(self, event):  # wxGlade: MyDialog.<event_handler>
        self.Close()
        event.Skip()

# end of class MyDialog

class MyApp(wx.App):
    def OnInit(self):
        self.dialog = MyDialog(None, wx.ID_ANY, "")
        self.SetTopWindow(self.dialog)
        self.dialog.ShowModal()
        self.dialog.Destroy()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
