#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.6 on Thu Jan 28 23:08:06 2021
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class DialogoConfiguracion(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyDialog.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        self.parent=args[0]
        wx.Dialog.__init__(self, *args, **kwds)
        self.button_1 = wx.Button(self, wx.ID_ANY, "Aceptar")
        self.text_ctrl_1 = wx.TextCtrl(self, wx.ID_ANY, "")
        self.text_ctrl_2 = wx.TextCtrl(self, wx.ID_ANY, "")
        self.window_1 = wx.ListBox(self, choices=['Wiener','Promedio','Mediana'],style = wx.LB_MULTIPLE )
        self.button_2 = wx.Button(self, wx.ID_ANY, "Cancelar")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.aceptar, self.button_1)
        self.Bind(wx.EVT_BUTTON, self.cancelar, self.button_2)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyDialog.__set_properties
        
        self.SetTitle("Configuración")
        self.text_ctrl_1.write(str(self.parent.configuracion["ppi"]))
        self.text_ctrl_2.write(str(self.parent.configuracion["BitCanal"]))
        
        if 'mediana' in self.parent.configuracion["Filtros"]:
            self.window_1.SetStringSelection('Mediana',True)
        if 'promedio' in self.parent.configuracion["Filtros"]:
            self.window_1.SetStringSelection('Promedio',True)
        if 'wiener' in self.parent.configuracion["Filtros"]:
            self.window_1.SetStringSelection('Wiener',True) 
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyDialog.__do_layout
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        label_1 = wx.StaticText(self, wx.ID_ANY, "Resolución(ppi)", style=wx.ALIGN_RIGHT)
        sizer_2.Add(label_1, 1, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 0)
        label_2 = wx.StaticText(self, wx.ID_ANY, "Profundidad(bit)")
        sizer_2.Add(label_2, 1, wx.ALIGN_CENTER_HORIZONTAL, 0)
        label_3 = wx.StaticText(self, wx.ID_ANY, "Filtros")
        sizer_2.Add(label_3, 1, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_2.Add(self.button_1, 1, wx.EXPAND, 0)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        sizer_3.Add(self.text_ctrl_1, 1, wx.EXPAND, 0)
        sizer_3.Add(self.text_ctrl_2, 1, wx.ALL | wx.EXPAND, 1)
        sizer_3.Add(self.window_1, 1, wx.EXPAND, 0)
        sizer_3.Add(self.button_2, 1, wx.EXPAND, 0)
        sizer_1.Add(sizer_3, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def aceptar(self, event):  # wxGlade: MyDialog.<event_handler>
        filtros=[]
        if self.window_1.IsSelected(0):
            filtros.append('wiener')
        if self.window_1.IsSelected(1):
            filtros.append('promedio')
        if self.window_1.IsSelected(2):
            filtros.append('mediana')
        configuracion={"BitCanal":int(self.text_ctrl_2.GetLineText(0)),"Filtros":filtros,"ppi":int(self.text_ctrl_1.GetLineText(0))}
        self.parent.configuracion=configuracion
        self.Close()
        self.Destroy()
        event.Skip()

    def cancelar(self, event):  # wxGlade: MyDialog.<event_handler>
        self.Close()
        self.Destroy()
        event.Skip()

# end of class MyDialog

class MyApp(wx.App):
    def OnInit(self):
        self.dialog = MyDialog(None, wx.ID_ANY, "")
        self.SetTopWindow(self.dialog)
        self.dialog.ShowModal()
        self.dialog.Destroy()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
