#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.6 on Thu Nov 19 16:21:44 2020
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class DialogoComparacionPlan(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyDialog.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SelectorPlan = wx.Button(self, wx.ID_ANY, "Navegar")
        self.CajaTextoPlan=wx.TextCtrl(self,value="",style=wx.TE_READONLY)
        self.SelectorEscan = wx.Button(self, wx.ID_ANY, "Navegar")
        self.CajaTextoEscan=wx.TextCtrl(self,value="",style=wx.TE_READONLY)
        self.text_ctrl_1 = wx.TextCtrl(self, wx.ID_ANY, "")
        self.text_ctrl_2 = wx.TextCtrl(self, wx.ID_ANY, "")
        self.text_ctrl_3 = wx.TextCtrl(self, wx.ID_ANY, "")
        self.button_1 = wx.Button(self, wx.ID_ANY, "Aceptar")
        self.button_2 = wx.Button(self, wx.ID_ANY, "Cancelar")
        
        self.resultado='cancelar'
        self.rutaPlan=''
        self.rutaEscan=''
        self.tole=2
        self.dist=2
        self.thres=20

        self.__set_properties()
        self.__do_layout()
        
        
        self.Bind(wx.EVT_BUTTON, self.buscarPlan, self.SelectorPlan)
        self.Bind(wx.EVT_BUTTON, self.buscarEscan, self.SelectorEscan)
        self.Bind(wx.EVT_BUTTON, self.aceptar, self.button_1)
        self.Bind(wx.EVT_BUTTON, self.cancelar, self.button_2)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyDialog.__set_properties
        self.SetTitle("Seleccion comparacion de plan")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyDialog.__do_layout
        grid_sizer_1 = wx.GridSizer(6, 2, 0, 0)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        label_1 = wx.StaticText(self, wx.ID_ANY, "Ruta Plan Calculado")
        grid_sizer_1.Add(label_1, 1, wx.ALIGN_CENTER, 0)
        sizerNav=wx.BoxSizer(wx.HORIZONTAL)
        sizerNav.Add(self.CajaTextoPlan,  1, wx.ALIGN_CENTER_VERTICAL | wx.ALL | wx.FIXED_MINSIZE, 10)
        sizerNav.Add(self.SelectorPlan, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL | wx.FIXED_MINSIZE, 20)
        grid_sizer_1.Add(sizerNav, 1, wx.EXPAND, 0)
        label_2 = wx.StaticText(self, wx.ID_ANY, "Ruta Plan Escaneado")
        grid_sizer_1.Add(label_2, 1, wx.ALIGN_CENTER, 0)
        sizerNav2=wx.BoxSizer(wx.HORIZONTAL)
        sizerNav2.Add(self.CajaTextoEscan,  1, wx.ALIGN_CENTER_VERTICAL | wx.ALL | wx.FIXED_MINSIZE, 10)
        sizerNav2.Add(self.SelectorEscan, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL | wx.FIXED_MINSIZE, 20)
        grid_sizer_1.Add(sizerNav2, 1, wx.EXPAND, 0)
        label_3 = wx.StaticText(self, wx.ID_ANY, "Tolerancia(%)")
        grid_sizer_1.Add(label_3, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_1.Add(self.text_ctrl_1, 0, wx.ALIGN_CENTER, 0)
        label_4 = wx.StaticText(self, wx.ID_ANY, "Distancia(mm)")
        grid_sizer_1.Add(label_4, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_1.Add(self.text_ctrl_2, 0, wx.ALIGN_CENTER, 0)
        label_5 = wx.StaticText(self, wx.ID_ANY, "Threshold(%)")
        grid_sizer_1.Add(label_5, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_1.Add(self.text_ctrl_3, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_1.Add(self.button_1, 1, wx.ALIGN_RIGHT, 0)
        grid_sizer_1.Add(self.button_2, 0, 0, 0)
        self.SetSizer(grid_sizer_1)
        grid_sizer_1.Fit(self)
        self.Layout()
        # end wxGlade
    def buscarPlan(self,event):
        dial=wx.FileDialog(self,name="Seleccione archivo",style=wx.FD_OPEN | wx.FD_FILE_MUST_EXIST)
        if dial.ShowModal()==wx.ID_OK:
            self.rutaPlan=dial.GetPath()
            self.CajaTextoPlan.SetValue(self.rutaPlan)
    def buscarEscan(self,event):
        dial=wx.FileDialog(self,name="Seleccione archivo",style=wx.FD_OPEN | wx.FD_FILE_MUST_EXIST)
        if dial.ShowModal()==wx.ID_OK:
            self.rutaEscan=dial.GetPath()
            self.CajaTextoEscan.SetValue(self.rutaEscan)
    def aceptar(self, event):  # wxGlade: MyDialog.<event_handler>
        self.resultado='aceptar'
        if self.text_ctrl_1.GetValue()!='':
            self.tole=float(self.text_ctrl_1.GetValue())
        if self.text_ctrl_2.GetValue()!='':
            self.dist=float(self.text_ctrl_2.GetValue())
        if self.text_ctrl_3.GetValue()!='':
            self.thres=float(self.text_ctrl_3.GetValue())
        self.Close()
        event.Skip()

    def cancelar(self, event):  # wxGlade: MyDialog.<event_handler>
        self.Close()
        event.Skip()

# end of class MyDialog

class MyApp(wx.App):
    def OnInit(self):
        self.dialog = DialogoComparacionPlan(None, wx.ID_ANY, "")
        self.SetTopWindow(self.dialog)
        self.dialog.ShowModal()
        self.dialog.Destroy()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
